ExUnit.start()
Code.require_file("support/snapshot_support.exs", __DIR__)
Code.require_file("support/test_support.exs", __DIR__)
Code.require_file("support/git_fixture.exs", __DIR__)
Code.require_file("support/github_forge_stub.exs", __DIR__)
Code.require_file("support/manifest.exs", __DIR__)
Code.require_file("support/mock_agent.exs", __DIR__)
Code.require_file("support/fake_human.exs", __DIR__)
